<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => "Brown Bear Car Wash",
                'location' => "Bekasi Raya Blok 3 No 2, Jakasetia",
                'rating' => 4.7,
                'features' => json_encode(["Promo", "Full Car Wash", "Detailing"]), // Encode the array
                'img_source' => asset('BrownBear.png'),
                'pricing' => 3,
                'queue' => 12,
                'capacity' => 10,
                'range' => 5.1,
            ],
            [
                'name' => "Elang Car Wash",
                'location' => "Jalan Galaxy Boulevard Blok 1 No 2, Jakasampurna",
                'rating' => 3.4,
                'features' => json_encode(["Full Car Wash"]),
                'img_source'=> asset('ElangCarWash.png'),
                'pricing' => 2,
                'queue' => 0,
                'capacity' => 4,
                'range'  => 3.2,
            ],
            [
                'name' => "Myjnia Kalinowa Car Wash",
                'location' => "Griya JM Blok 17 No 269, Jatiasih",
                'rating' => 4.5,
                'features' => json_encode(["Promo", "Full Car Wash", "Interior"]),
                'img_source'=> asset('MyjniaCarWash.png'),
                'pricing' => 2,
                'queue' => 5,
                'capacity' => 7,
                'range' => 6.9,
            ],

            [
                'name' => "Arm Detailing Coating",
                'location' => "Ruko Rose Garden No.1 No.1, Jaka Setia",
                'rating' => 4.0,
                'features' => json_encode(["Detailing", "Coating", "Paint Protection Film"]),
                'img_source' =>asset('ArmDetailing.png'),
                'pricing' => 4,
                'queue' => 1,
                'capacity' => 2,
                'range' => 4.2,
            ],
            [
                'name' => "AutoGlaze Express Grand Galaxy Park",
                'location' => "Grand Galaxy Boulevard No. 1 Lantai Basement, Parking Lot B.08, Jaka Setia",
                'rating' => 3.8,
                'features' => json_encode(["Full Car Wash", "Detailing", "Polishing", "Interior"]),
                'img_source'=> asset('AutoGlaze.png'),
                'pricing' => 3,
                'queue' => 0,
                'capacity' => 3,
                'range' => 3.8,
            ],
            [
                'name' => "AutoSpa Bekasi",
                'location' => "Taman Galaxy Raya No.295, Jaka Setia",
                'rating' => 4.9,
                'features' => json_encode(["Full Car Wash", "Paint Protection Film", "Interior", "Coating", "Polishing", "Detailing", "Undercarriage"]),
                'img_source'=> asset('AutoSpa.png'),
                'pricing' => 4,
                'queue' => 5,
                'capacity' => 8,
                'range' => 9.8,
            ],
            [
                'name' => "Azka Premium Polish",
                'location' => "Ruko Taman Galaxy Raya, Jaka Setia",
                'rating' => 4.3,
                'features' => json_encode(["Polishing", "Paint Protection Film", "Coating", "Detailing"]),
                'img_source'=> asset('AzkaPremiumPolish.png'),
                'pricing' => 4,
                'queue' => 2,
                'capacity' => 3,
                'range' => 12.5,
            ],
            [
                'name' => "Car Wash Gue II",
                'location' => "Jl. Raya Pekayon No.12, Jaka Setia",
                'rating' => 4.4,
                'features' => json_encode(["Full Car Wash", "Polishing", "Coating", "Detailing", "Undercarriage", "Waiting Lounge"]),
                'img_source'=> asset('CarWashGue.png'),
                'pricing' => 3,
                'queue' => 5,
                'capacity' => 7,
                'range' => 7,
            ],
            [
                'name' => "Delta Car Wash Galaxy",
                'location' => "Ruko Taman Galaxy Raya, Jaka Setia",
                'rating' => 3.0,
                'features' => json_encode(["Full Car Wash", "Detailing"]),
                'img_source'=> asset('DeltaCarWash.png'),
                'pricing' => 1,
                'queue' => 5,
                'capacity' => 9,
                'range' => 3.2,
            ],
            [
                'name' => "DOW Auto Wrap",
                'location' => "Nusa Indah Raya No.6 Blok W, Jaka Setia",
                'rating' => 5.0,
                'features' => json_encode(["Detailing", "Coating", "Paint Protection Film", "Interior"]),
                'img_source'=> asset('DOWAutoWrap.png'),
                'pricing' => 4,
                'queue' => 3,
                'capacity' => 3,
                'range' => 7.7,
            ],
            [
                'name' => "Dr Gloss Clean & Protect",
                'location' => "Ruko Grand Galaxy City Block AR 1 No.50, Jaka Setia",
                'rating' => 4.6,
                'features' => json_encode(["Detailing", "Coating", "Paint Protection Film", "Interior"]),
                'img_source'=> asset('DrGloss.png'),
                'pricing' => 4,
                'queue' => 2,
                'capacity' => 3,
                'range' => 6.0,
            ],
            [
                'name' => "Dhaff Coffee & Car Wash",
                'location' => "Jl. Raya Pekayon No.5, Pekayon Jaya",
                'rating' => 4.1,
                'features' => json_encode(["Full Car Wash", "Detailing", "Undercarriage", "Waiting Lounge"]),
                'img_source'=> asset('DhafCoffeeCarWash.png'),
                'pricing' => 3,
                'queue' => 5,
                'capacity' => 6,
                'range' => 7.8,
            ],
            [
                'name' => "Freya Car Wash",
                'location' => "Grand Galaxy, Jl. Surya Raya, Jaka Setia",
                'rating' => 3.5,
                'features' => json_encode(["Full Car Wash", "Detailing", "Undercarriage"]),
                'img_source'=> asset('FreyaCarWash.png'),
                'pricing' => 2,
                'queue' => 1,
                'capacity' => 5,
                'range' => 4.4,
            ],
            [
                'name' => "Grand Galaxy Car Wash",
                'location' => "Jl. Pulo Sirih Bar. Raya, Jaka Setia",
                'rating' => 4.8,
                'features' => json_encode(["Full Car Wash", "Interior"]),
                'img_source'=> asset('GalaxyCarWash.png'),
                'pricing' => 2,
                'queue' => 1,
                'capacity' => 8,
                'range' => 5.2,
            ],
            [
                'name' => "Garage Auto Studio Galaxy",
                'location' => "Jl. Taman Galaxy Raya No.20 Blok H, Jaka Setia",
                'rating' => 4.9,
                'features' => json_encode(["Polishing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('GASGarage.png'),
                'pricing' => 4,
                'queue' => 2,
                'capacity' => 2,
                'range' => 2.2,
            ],
            [
                'name' => "Gorillaz Galaxy",
                'location' => "Jl. Taman Galaxy Raya, Jaka Setia",
                'rating' => 4.3,
                'features' => json_encode(["Polishing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('Gorillaz.png'),
                'pricing' => 3,
                'queue' => 1,
                'capacity' => 2,
                'range' => 5.5,
            ],
            [
                'name' => "Karonta Car Wash",
                'location' => "Jl. Pulo Sirih Utama No.169, Jaka Setia",
                'rating' => 2.3,
                'features' => json_encode(["Full Car Wash", "Interior", "Coating"]),
                'img_source'=> asset('KarontaCarWash.png'),
                'pricing' => 2,
                'queue' => 3,
                'capacity' => 5,
                'range' => 3.7,
            ],
            [
                'name' => "Tri Claviya Car Wash",
                'location' => "Jl. Pulo Sirih Utama No.23, Jaka Setia",
                'rating' => 4.4,
                'features' => json_encode(["Full Car Wash", "Interior", "Coating", "Undercarriage"]),
                'img_source'=> asset('TriClaviya.png'),
                'pricing' => 3,
                'queue' => 3,
                'capacity' => 6,
                'range' => 8.2,
            ],
            [
                'name' => "Rizka Car Wash",
                'location' => "Jl. Pulo Sirih Utama Blok BV No. 22, Jaka Setia",
                'rating' => 4.8,
                'features' => json_encode(["Full Car Wash", "Interior", "Undercarriage"]),
                'img_source'=> asset('RizkaCarWash.png'),
                'pricing' => 2,
                'queue' => 2,
                'capacity' => 2,
                'range' => 7.5,
            ],
            [
                'name' => "Otopia Coating & Detailing",
                'location' => "Galaxy City, Jl. Boulevard Raya No.37, Jaka Setia",
                'rating' => 4.9,
                'features' => json_encode(["Detailing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('Otopia.png'),
                'pricing' => 3,
                'queue' => 2,
                'capacity' => 2,
                'range' => 6.3,
            ],
            [
                'name' => "SCUTO Galaxy",
                'location' => "Ruko Taman Galaxy Blok AR.2 No.16, Jaka Setia",
                'rating' => 4.7,
                'features' => json_encode(["Detailing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('SCUTO.png'),
                'pricing' => 4,
                'queue' => 2,
                'capacity' => 3,
                'range' => 4.4,
            ],
            [
                'name' => "Spyder Auto Detailing",
                'location' => "Jl. Taman Galaxy Raya No.14 Blok A, Jaka Setia",
                'rating' => 5.0,
                'features' => json_encode(["Detailing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('Spyder.png'),
                'pricing' => 4,
                'queue' => 3,
                'capacity' => 3,
                'range' => 5.6,
            ],
            [
                'name' => "Mark Auto Detailing",
                'location' => "Ruko Galaxy City Blok RGK 582, Jaka Setia",
                'rating' => 5.0,
                'features' => json_encode(["Detailing", "Interior", "Coating", "Paint Protection Film"]),
                'img_source'=> asset('MarkDetailing.png'),
                'pricing' => 4,
                'queue' => 3,
                'capacity' => 3,
                'range' => 5.6,
            ],
            [
                "name" => "The Legend Car Wash", 
                "location" => "Nagrak, Gunung Putri, Bogor Regency", 
                "rating" => 3.9, 
                "features" => json_encode(["Full Car Wash, Polishing, Coating, Undercarriage"]),  
                'img_source'=> asset('LegendCarWash.png'),
                "pricing" => 2,
                'queue' => 6,
                'capacity' => 7,
                "range" => 12.4,  
            ],
            [
                "name" => "Banyu Bening Premium Car Wash",  
                "location" => "Jl. Transyogi, Nagrak, Cileungsi",
                "rating" => 4.1, 
                "features" => json_encode(["Full Car Wash, Undercarriage"]),
                'img_source'=> asset('BanyuBening.png'),
                "pricing" => 2,
                'queue' => 8,
                'capacity' => 8,
                "range" => 11.9,
            ]
        ];

        DB::table('places')->insert($data);
    }
}
